### ISSUE TITLE
Error Feature Generation

### ISSUE THREAD

**Issue by ttmgr** [ziyewang/COMEBin#4]
Hi again, 

after fixing the path issue I am getting a different error by now:

Traceback (most recent call last):
  File "main.py", line 368, in <module>
    main()
  File "main.py", line 288, in main
    train_CLmodel(logger,args)
  File "/COMEBin/COMEBin/train_CLmodel.py", line 235, in train_CLmodel
    simclr.train_addpretrain(train_loader, dataset, namelist)
  File "/COMEBin/COMEBin/simclr.py", line 299, in train_addpretrain
    top1, top5 = accuracy(logits, labels, topk=(1, 5))
UnboundLocalError: local variable 'logits' referenced before assignment
Something went wrong with running training network. Exiting.

Is there a way to fix this issue?

Best,
tim

**Comment by ziyewang** [comment]
Hi,

The issue may be due to the default parameters not being suitable for datasets with fewer than 1024 contigs. You can retry by adding this option when running `run_comebin.sh`: 
"-b INT          batch size for training process (default=1024)" and the numerical value can be set to the actual number of contigs in the specific dataset.

Best,
Ziye

**Comment by ziyewang** [comment]
Hi,

Besides adjusting the parameters, updating to the latest version (v1.0.4) can also resolve this issue.

Best,
Ziye
